script: "bundle exec rake spec"
rvm:
  - 1.9.2
  - 1.9.3
#  - ruby-head
#  - jruby-19mode
gemfile:
#  - gemfiles/Gemfile.rails-3.0.10
  - gemfiles/Gemfile.rails-3.1.10
  - gemfiles/Gemfile.rails-3.2.11
env:
  - DB=sqlite3
  - DB=mysql
  - DB=mysql2
matrix:
  exclude:
    - rvm: 1.9.3
      env: DB=mysql
      gemfile: gemfiles/Gemfile.rails-3.1.10
    - rvm: 1.9.3
      env: DB=mysql
      gemfile: gemfiles/Gemfile.rails-3.2.11
