rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - ree
gemfile:
  - gemfiles/Gemfile.rails-2.3.14
  - gemfiles/Gemfile.rails-3.0.10
  - gemfiles/Gemfile.rails-3.1.1
  - gemfiles/Gemfile.rails-3.2.3
env:
  - DB=sqlite3
  - DB=mysql
  - DB=mysql2
