sqlite:
  :adapter: sqlite
  :dbfile: schema_comments_test.sqlite.db
sqlite3:
  :adapter: sqlite3
  :dbfile: schema_comments_test.sqlite3.db
mysql:
  adapter: mysql
  encoding: utf8
  username: root
  password:
  socket: /opt/local/var/run/mysql5/mysqld.sock
  database: schema_comments_test
