sqlite3:
  :adapter: sqlite3
  :database: ":memory:"
mysql:
  adapter: mysql
  encoding: utf8
  username: root
  password:
  database: schema_comments_mysql_test
mysql2:
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  database: schema_comments_mysql2_test
